# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory to /app
WORKDIR /app

# Copy the pom.xml file and install dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

# Copy the rest of the application files
COPY src/ /app/src/

# Build the application
RUN mvn package -DskipTests

# Set the entry point
ENTRYPOINT ["java", "-jar", "target/simple-java-maven-app-master.jar"]
